### ISSUE TITLE
cfengine compile error

### ISSUE THREAD

**Issue by mohamedgalal99** [enigmagroup/enigmabox-openwrt#1]
when i try to build image, cfengine through error, when i try to compile it separately it works fine, but during openwrt/enigma make through error:
make[4]: Entering directory '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7'
make  all-recursive
make[5]: Entering directory '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7'
Making all in libcompat
make[6]: Entering directory '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7/libcompat'
  CC       generic_at.lo
In file included from /root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/route.h:26:0,
                 from ../libutils/platform.h:364,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/if.h:71:2: error: expected identifier before numeric constant
  IFF_UP    = 1<<0,  /* sysfs */
  ^
In file included from /root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/route.h:26:0,
                 from ../libutils/platform.h:364,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/if.h:169:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^
In file included from ../libutils/platform.h:344:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/net/if.h:65:8: note: originally defined here
 struct ifmap {
        ^
In file included from /root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/route.h:26:0,
                 from ../libutils/platform.h:364,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/if.h:203:8: error: redefinition of 'struct ifreq'
 struct ifreq {
        ^
In file included from ../libutils/platform.h:344:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/net/if.h:77:8: note: originally defined here
 struct ifreq {
        ^
In file included from /root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/route.h:26:0,
                 from ../libutils/platform.h:364,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/if.h:252:8: error: redefinition of 'struct ifconf'
 struct ifconf  {
        ^
In file included from ../libutils/platform.h:344:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/net/if.h:117:8: note: originally defined here
 struct ifconf {
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:26:3: error: expected identifier before numeric constant
   IPPROTO_IP = 0,  /* Dummy protocol for TCP  */
   ^
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:79:8: error: redefinition of 'struct in_addr'
 struct in_addr {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:14:8: note: originally defined here
 struct in_addr { in_addr_t s_addr; };
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:157:8: error: redefinition of 'struct ip_mreq'
 struct ip_mreq  {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:248:8: note: originally defined here
 struct ip_mreq
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:162:8: error: redefinition of 'struct ip_mreqn'
 struct ip_mreqn {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:254:8: note: originally defined here
 struct ip_mreqn
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:168:8: error: redefinition of 'struct ip_mreq_source'
 struct ip_mreq_source {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:261:8: note: originally defined here
 struct ip_mreq_source {
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:174:8: error: redefinition of 'struct ip_msfilter'
 struct ip_msfilter {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:267:8: note: originally defined here
 struct ip_msfilter {
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:186:8: error: redefinition of 'struct group_req'
 struct group_req {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:278:8: note: originally defined here
 struct group_req {
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:191:8: error: redefinition of 'struct group_source_req'
 struct group_source_req {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:283:8: note: originally defined here
 struct group_source_req {
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:197:8: error: redefinition of 'struct group_filter'
 struct group_filter {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:289:8: note: originally defined here
 struct group_filter {
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:209:8: error: redefinition of 'struct in_pktinfo'
 struct in_pktinfo {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:300:8: note: originally defined here
 struct in_pktinfo
        ^
In file included from ../libutils/platform.h:365:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/in.h:217:8: error: redefinition of 'struct sockaddr_in'
 struct sockaddr_in {
        ^
In file included from ../libutils/platform.h:345:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/in.h:16:8: note: originally defined here
 struct sockaddr_in
        ^
In file included from ../libutils/platform.h:366:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/linux/ip.h:85:8: error: redefinition of 'struct iphdr'
 struct iphdr {
        ^
In file included from ../libutils/platform.h:347:0,
                 from generic_at.c:25:
/root/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_musl-1.1.10/include/netinet/ip.h:25:8: note: originally defined here
 struct iphdr {
        ^
Makefile:525: recipe for target 'generic_at.lo' failed
make[6]: *** [generic_at.lo] Error 1
make[6]: Leaving directory '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7/libcompat'
Makefile:595: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7'
Makefile:519: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7'
Makefile:61: recipe for target '/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7/.built' failed
make[3]: *** [/root/openwrt/build_dir/target-i386_i486_musl-1.1.10/cfengine-3.6.0erc-build7/.built] Error 2
make[3]: Leaving directory '/root/openwrt/feeds/enigmabox/cfengine'
package/Makefile:191: recipe for target 'package/feeds/enigmabox/cfengine/compile' failed
make[2]: *** [package/feeds/enigmabox/cfengine/compile] Error 2
make[2]: Leaving directory '/root/openwrt'
package/Makefile:188: recipe for target '/root/openwrt/staging_dir/target-i386_i486_musl-1.1.10/stamp/.package_compile' failed
make[1]: *** [/root/openwrt/staging_dir/target-i386_i486_musl-1.1.10/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/openwrt'
/root/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by enigmagroup** [comment]
I bet this has something todo with this shiny-blinky new musl shit. Well, I haven't tested it yet. I propose you use uClibc as it has been the default before.

Advanced configuration options -> Toolchain Options -> C Library implementation -> Use uClibc.

I'm sorry about that. I have to retest everything and write patches. As you may have seen in the OpenWrt repo, I'm not the only one struggling with this ;)

**Comment by enigmagroup** [comment]
I mentioned it in the Readme: https://github.com/enigmagroup/enigmabox-openwrt/commit/408ae7705000500fac27d0cbbad8b00da8b6acdc

Thank you for testing. Since I already updated my config, I forgot to mention this in the Readme too.
