### ISSUE TITLE
No more access to encrypted internet

### ISSUE THREAD

**Issue by Meisterzunge** [enigmagroup/enigmabox-openwrt#12]
I had a working banana pi enigmabox with a 30 days subscription.

For testing purposes I hat changed my routers ip subnet (from 192.168.0.0 to 192.168.1.0) and tested the enigmabox with it.

Than I switched back to the routers original IP-subnet (192.168.0.0), formated my enigmabox sd card and have writtem the OpenWRT-image to sd card again (Means complete reinitialization).
I have imported the SSL certificates and set up the password for the webinterface but the box can't access the encrypted internet!? (Standard internet is still working).

Don't know if it helps: Heres the error log of the SSH-command cjdnslog ‘’:
[SSH Log.docx](https://github.com/enigmagroup/enigmabox-openwrt/files/72407/SSH.Log.docx)

**Comment by enigmagroup** [comment]
That's the cjdns log and that doesn't help. what's your hostid? maybe its already expired?

**Comment by Meisterzunge** [comment]
Don't know what it was, but it is running. I can imagine that the router had not send it's dchp-settings to the client (enigmabox).
