### ISSUE TITLE
Private fork updated to 2019, soon published

### ISSUE THREAD

**Issue by erdoukki** [enigmagroup/enigmabox-openwrt#17]
Hello,
Stay tuned, I get the full client side all working with all packages upgraded (huge work) on 2019 OpenWrt Based.
All tested on EspressoBin Board ready to use, binaries, sources, box...
Available to sell to who need (EBin, and, services for customized installation, and IT parts...)

I will published all the sources locked by a false and illegal ND (Nor GNU, FSF and french specialized advocates help me on this... So bad!).

The sources are available in a private fork already, just waiting from too long and locking other better project CyberMind already work from 30 years on...

So, today, I will published the full fork of the clients side, OS, packages, binaries.

You can get in touch if you want an EspressoBin Board ready to use with the latest binary.

If the old team need some delay, or may had a good reason to prevent me on this, for a delay...
Get in touch, please!

Thx for the works...

I had planned to make a crowd about this project, but I am stuck in another's of my own philosophy...

Stay tuned...
And remember UNIX mantra, live free, or die.

Gandalf
@enigmagroup 
@Conjurers

**Comment by oneil4** [comment]
Thank you, I can't wait to see it, a great project!

**Comment by erdoukki** [comment]
published

**Comment by erdoukki** [comment]
https://github.com/CyberMind-FR/enigmabox-openwrt-public

done

**Comment by erdoukki** [comment]
done

published
here

https://github.com/CyberMind-FR/enigmabox-openwrt-public

**Comment by erdoukki** [comment]
> done
> 
> published here
> 
> https://github.com/CyberMind-FR/enigmabox-openwrt-public

Ready to use hardware with globalscale custom development board available at world selling on demand !

any customisation or addons also available at paid service...

will plan also to re-refresh with latest openwrt master os release...
can accelerate the planed delay with sponsoring...

all at www.CyberMind.FR

docu;entation, tutorial or demonstration and custom teach session also possible, ask contact@cybermind.fr or ask at gandalf@gk2.net

Edit:
If you also need a P2P like mesh main server to really revive this box with nowadays protocols, just get in touch and help this by funding my work or ask for a paid help to make it been quicky available...
