### ISSUE TITLE
select country

### ISSUE THREAD

**Issue by mohamedgalal99** [enigmagroup/enigmabox-openwrt#4]
Hi,

After compile enigma-openwrt, I run it on virtualbox and attach other vm to it.
- when I get select country page, no countries listed in it. I don't know where is the error
- webinterface mail box, ask mail@box password, what's default passwd

thx

**Comment by enigmagroup** [comment]
> when I get select country page, no countries listed in it. I don't know where is the error

Available countries are fetched from the server and so only being displayed when there is a subscription imported.

> webinterface mail box, ask mail@box password, what's default passwd

Default password is random scrambled. You can define it here: http://box/passwords/mailbox/
