### ISSUE TITLE
Enigmabox-OpenWRT wlan0 mesh-mode not working

### ISSUE THREAD

**Issue by gellenburg** [enigmagroup/enigmabox-openwrt#6]
Related to https://github.com/enigmagroup/enigmasuite/issues/4.

> With an attached ALFA AWUS036NEH to my Enigmabox, and WLAN Settings set to "mesh", I see a new cjdns ad-hoc network, but no other Enigmaboxes can connect.
> 
> Looking at /box/cjdroute.conf there is no…
> 
> ```
> "bind": "wlan0",
> "beacon": 2,
> ```
> … entry in the config.
> 
> This is affecting Enigmaboxes built with BananaPis.

**Comment by enigmagroup** [comment]
Issue is fixed, will deploy the new image overnight.

**Comment by blobgo** [comment]
If it is fixed I assume this issue can be closed. :smiley:

**Comment by gellenburg** [comment]
yep. it's fixed. hopefully the bananapi firmware will be updated soon. can't wait to test it out.

**Comment by enigmagroup** [comment]
Oh it is! All firmwares are compiled at the same time.

**Comment by gellenburg** [comment]
Hello!

 

New message, please read <http://andalan-nusantara.com/spoken.php?pc7ve>

 

george@ellenburg.org

**Comment by enigmagroup** [comment]
lol no

**Comment by gellenburg** [comment]
WTF?! Ugh.

**Comment by gellenburg** [comment]
Hello!

 

New message, please read <http://hamiltonfire.net/step.php?be>

 

george@ellenburg.org

**Comment by enigmagroup** [comment]
Eeek, this url redirects to http://nextbusinessnews.com/ ....

**Comment by gellenburg** [comment]
why would you even click it? my email address has been spoofed. I have 1500 mailer daemon messages in my inbox right now. don't click random links in email messages! :-)

Sent from my Cyanogen phone

On Feb 25, 2016 4:11 AM, enigmagroup <notifications@github.com> wrote:

Eeek, this url redirects to http://nextbusinessnews.com/ ....

**Comment by gellenburg** [comment]
Hello, That stuff is just gorgeous, you have to read about it more at <http://suwyltafri.demoweb.net/aelksh>

Sent from a prehistoric stone tablet, george@ellenburg.org
